### ISSUE TITLE
Link broken on arxiv and PDF

### ISSUE THREAD

**Issue by mmattamala** [TIERS/tiers-lidars-dataset#1]
Hi, just wanted to report that both the arxiv abstract and the link in the PDF point to https://github.com/TIERS/tiers-lidars-dataset, and not to this repo.

Thanks for the dataset, we are looking forward to using it in our lab :)

Cheers

**Comment by jopequ** [comment]
Hi, thanks for pointing this out, we just renamed the repo. Glad to hear it may be of use for your work! ;)
