### ISSUE TITLE
How do I adapt lego-loam for this dataset?

### ISSUE THREAD

**Issue by yinhaosen** [TIERS/tiers-lidars-dataset#10]
As far as I know, lego-loam original code outputs slam pose based on z-x-y coordinate instead of x-y-z coordinate so how does it work with your dataset as the trajectory comparisons picture shown on the home page?

**Comment by Qingq-li** [comment]
> 

 Yes, the Lego-LOAM has a different coordinate system from other methods (e.g.FAST-LIO and LIO-Llivox). Therefore, we added a TF transform on the results of Lego-loam to align the trajectory with others.
