### ISSUE TITLE
Is indoor ground truth from LIO SLAM method?

### ISSUE THREAD

**Issue by Cc19245** [TIERS/tiers-lidars-dataset#12]
Hi, thanks for your great work!

Is indoor ground truth from LIO SLAM method such as FAST-LIO2?  If I want to use indoor dataset to evaluate the trajectory accuracy of my LIO algorithm, is the ground truth accurate enough?

**Comment by Qingq-li** [comment]
Hi, thanks for your interest in our work. We have open-sourced a [new enhanced dataset](https://github.com/TIERS/tiers-lidars-dataset-enhanced ) where we use new methods to generate and evaluate ground-truth trajectory. You can check the related paper for more information here: https://arxiv.org/abs/2210.00812.
