### ISSUE TITLE
Extrinic parameter between Motion Cap and LiDAR

### ISSUE THREAD

**Issue by yuhui-xie** [TIERS/tiers-lidars-dataset#5]
May I ask How can I get the Extrinic parameter between Motion Cap and LiDAR?

**Comment by Qingq-li** [comment]
> May I ask How can I get the Extrinic parameter between Motion Cap and LiDAR?

Hi, we gathered data with our system in different environments, so the extrinsic parameters between Lidars and Motion Cap are also different. We didn't check the extrinsic parameter between Lidars and OptiTrack in each sequence. However, you can check the evolution tools (https://github.com/MichaelGrupp/evo) to get the extrinsic parameters by aligning your SLAM result and OptiTrack trajectory. 
In future, we plan to publish the ground truth trajectory for each sensor.
