### ISSUE TITLE
problem in gt timestamp and bag timestamp

### ISSUE THREAD

**Issue by yuhui-xie** [TIERS/tiers-lidars-dataset#7]
Hi, thanku for u open dataset.
When I use Tiers, I found that it seems that the gt timestamp can't be aligned with bag timestamp, the bag I use is indoor02.bag and gt I used is located in here https://github.com/TIERS/tiers-lidars-dataset/blob/main/data/ground_truth/indoor02_optitrack.csv.

gt starts with 1645371291.95999, end  with 1645371332.29002
VLP start with 1645463118.1386, end with 1645463160.39853
it seems that There is no overlap between them at all

**Comment by Qingq-li** [comment]
Hi, thanks for pointing out this error. We have updated the ground truth for the indoor02 sequence.

BTW, the ground truth topic  "/vrpn_client_node/*" published by the MOCAP system is also included in rosbag.
