### ISSUE TITLE
did you use inbuilt IMU's from Ouster and Livox for mapping?

### ISSUE THREAD

**Issue by arjunskumar** [TIERS/tiers-lidars-dataset#9]

**Comment by Qingq-li** [comment]
hanks for your interest in our dataset. 
Yes, we utilized the built-in IMU of each Livox and Ouster LiDAR when we test SLAM methods such as Fast LIO, and LIO-LIVOX.  In theory, we also can use built-in IMUs from other LiDARs after careful calibration.

**Comment by srinivasrama** [comment]
@Qingq-li , Thanks,  could you mention how  you calibrated lidar-imu ?

**Comment by arjunskumar** [comment]
@Qingq-li ,  Thanks, can you explain how you did Lidar-IMU calibration?

**Comment by Qingq-li** [comment]
Hi, the extrinsic parameter between each lidar and its build-in IMU is public available from factory instruction. For the intrinsic of IMU, methods like LIO-Livox and Fast LIO will estimate the biases and noise distribution automatically. Therefore, we don't have to calibrate by ourselves if we just want to compare performance between different methods with parameters from the factory and STOA SLAM methods. 
You can check the following repo for more information:
      - https://github.com/hku-mars/FAST_LIO/blob/main/src/IMU_Processing.hpp
      - https://github.com/Livox-SDK/LIO-Livox/blob/master/src/lio/Estimator.cpp

Furthermore,  we also calibrate and verify the extrinsic and intrinsic parameters with open-source calibration tools. Here, I recommend one targetless calibration tool, LIDAR_IMU_INIT (https://github.com/hku-mars/LiDAR_IMU_Init), which is easy to use and the code is well-organized.

**Comment by arjunskumar** [comment]
@Qingq-li , I have used LIDAR_IMU_INIT, but not getting good results as my lidar and imu are already mounted on a wheeled robot

**Comment by yinhaosen** [comment]
Could we use velodyne lidar data running with livox imu data for lio-sam?

**Comment by Qingq-li** [comment]
> Could we use velodyne lidar data running with livox imu data for lio-sam?

Hi, unfortunately, as the built-in IMU of LIVOX and Ouster are both 6-axis IMUs, we cannot use it directly on LIO-SAM (https://github.com/TixiaoShan/LIO-SAM) which only works with a 9-axis IMU.

**Comment by arjunskumar** [comment]
There is [6axis version of liosam](https://github.com/JokerJohn/LIO_SAM_6AXIS)

**Comment by yinhaosen** [comment]
Another follow-up question I found recently is the timestamp of velodyne lidar data is quite different from that of livox ima data. Didn’t they record simultaneously?

**Comment by Qingq-li** [comment]
> Yes, we did not synchronize the timestamp between different sensors. The timestamp in ROS messages from Livox and Ouster LiDARs are generated from their own oscillators. We noticed the problem, so we provided an enhanced dataset recently in which sensors are synchronized with PTP. You can find the enhanced version with the link https://github.com/TIERS/tiers-lidars-dataset-enhanced.

**Comment by yinhaosen** [comment]
啊这
